version: '3.9'

services:
    app:
        build:
            context: .
        image: template_app
        container_name: endpoints
        restart: unless-stopped
        env_file:
            - .env_dev
        ports:
            - "${ENDPOINT_PORT}:${ENDPOINT_PORT}"
        command: gunicorn -b ${ENDPOINT_HOST}:${ENDPOINT_PORT} -k uvicorn.workers.UvicornWorker app.main:app --workers=2